### ISSUE TITLE
Test build fails for Android and iOS tests

### ISSUE THREAD

**Issue by petros-chariskos** [DataDog/dd-sdk-kotlin-multiplatform#108]
### Describe the bug

The Android and iOS tests fail when adding a test within the `:sample:shared` module and use the `:check` command to run the tests. This is a major issue if we want to write platform specific tests or even when using the Kotest framework to write all of our tests. Look further below to see how to easily reproduce the issue.

### Reproduction steps

How to reproduce:

1. Download this repository
2. In the `:sample:shared` module, create a `commonTest/kotlin` directory and add the `org.jetbrains.kotlin:kotlin-test` dependency in gradle in commonTest dependencies
3. Write a sample test
4. Both `./gradlew sample:shared:check` and `./gradlew sample:shared:check -PtargerOs=iOS` fail with:
```
ld: warning: ignoring duplicate libraries: '-ldl'
ld: framework 'DatadogObjc' not found
```

### Device logs

./gradlew sample:shared:check -PtargerOs=ios
Type-safe project accessors is an incubating feature.

> Configure project :core
w: Kotlin Multiplatform <-> Android Gradle Plugin compatibility issue:
The applied Android Gradle Plugin version (8.6.1) is higher 
than the maximum known to the Kotlin Gradle Plugin.
Tooling stability in such configuration isn't tested, please report encountered issues to https://kotl.in/issue

Minimum supported Android Gradle Plugin version: 7.1
Maximum tested Android Gradle Plugin version: 8.5

To suppress this message add 'kotlin.mpp.androidGradlePluginCompatibility.nowarn=true' to your gradle.properties

Credentials config file is not found, using empty values

> Task :sample:shared:linkDebugTestIosSimulatorArm64 FAILED
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
Please try to disable compiler caches and rerun the build. To disable compiler caches, add the following line to the gradle.properties file in the project's root directory:
    
    kotlin.native.cacheKind.iosSimulatorArm64=none
    
Also, consider filing an issue with full Gradle log here: https://kotl.in/issue
The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: warning: ignoring duplicate libraries: '-ldl'
ld: framework 'DatadogObjc' not found

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:shared:linkDebugTestIosSimulatorArm64'.
> Compilation finished with errors

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
39 actionable tasks: 4 executed, 35 up-to-date

### Affected SDK versions

0.0.3

### Latest working SDK version

-

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Kotlin version

2.0.21

### Gradle / AGP version

8.5.2

### iOS Integration Methods

XCFramework

**Comment by 0xnm** [comment]
Hello @petros-chariskos! As error says, for running the tests you need to link native iOS pods. You can check how it is done in other modules, e.g. https://github.com/DataDog/dd-sdk-kotlin-multiplatform/blob/4d60ee727cf0bccfde69ebf23ab7ed9fcb0c9b0f/features/webview/build.gradle.kts#L37-L52.

**Comment by petros-chariskos** [comment]
Indeed, though, the other Kotlin Multiplatform modules are making use of the `cocoapods` integration, while the `:sample:shared` module uses the iOS regular framework distribution. There is no sample code on how to address the failing tests with the regular framework. The "how to reproduce" section I wrote above is exposing this problem in your current sample app.

**Comment by 0xnm** [comment]
Great that the issue is solved, we will look into docs update.

**Comment by petros-chariskos** [comment]
No, the issue is not solved.
The issue has to do with the fact that running platform specific tests in a Kotlin Multiplatform module with the iOS regular framework distribution will always fail if the `com.datadoghq:dd-sdk-kotlin-multiplatform-logs` is added in the `commonMain` dependencies.

**Comment by 0xnm** [comment]
@petros-chariskos Can you please then share an error you are getting?

**Comment by petros-chariskos** [comment]
Everything is written in the initial post. I recite here:

```
The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: warning: ignoring duplicate libraries: '-ldl'
ld: framework 'DatadogObjc' not found

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':sample:shared:linkDebugTestIosSimulatorArm64'.
```

(hopefully a human is addressing this issue and not a bot because I am saying the same things in 3 different posts)

**Comment by 0xnm** [comment]
@petros-chariskos The issue is exactly as I explained in the post before: you need to link the necessary framework. In case of unit-testing on iOS Kotlin Multiplatform creates a special executable, so the way shared framework is distributed doesn't really matter.

Here is an example of the successful test https://github.com/DataDog/dd-sdk-kotlin-multiplatform/compare/develop...nogorodnikov/example-shared-tests (I followed the steps you posted in your initial message, with only difference that `./gradlew :sample:shared:iosSimulatorArm64Test` is used to run the test instead of the `check`, because this test is not ready for the Android platform).

If you still experience the issues, please post more details about your setup or provide a reproducible example.

**Comment by petros-chariskos** [comment]
@0xnm thank you for a detailed answer! This solution is working, you can close this issue.
